CP=commons-logging-1.1.3.jar:httpclient-4.3.jar:httpcore-4.3.jar:json-simple-1.1.1.jar:gson-2.2.4.jar:guava-15.0.jar:.

test:TestUploadAPIServlet.java
	javac -cp $(CP) TestUploadAPIServlet.java
	java -cp  $(CP) TestUploadAPIServlet
